array_width = 160
binop_separator = "Back"
chain_width = 100
combine_control_expr = false
comment_width = 160
fn_call_width = 120
fn_single_line = true
format_code_in_doc_comments = true
max_width = 160
newline_style = "Unix"
reorder_impl_items = true
single_line_if_else_max_width = 100
trailing_comma = "Never"
use_try_shorthand = true
